apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - order-api/deployment.yaml
  - query-api/deployment.yaml
  - orderbook-worker/deployment.yaml
  - traefik/order-api-ingressroute.yaml
